// Question Pool: 25 Easy, 25 Medium, 25 Hard
// Active Quiz selects 10 Easy, 10 Medium, 5 Hard = 25 Questions total (50 Max Points)

const QUESTIONS = {
  easy: [
    { id:'e1', text:'What does AI stand for?', options:['Automated Internet','Artificial Intelligence','Advanced Information','Automatic Integration'], correct:'B' },
    { id:'e2', text:'What is the "brain" of a computer commonly called?', options:['RAM','Hard Disk','CPU','Monitor'], correct:'C' },
    { id:'e3', text:'What does RAM stand for?', options:['Read Access Memory','Random Access Memory','Rapid Access Module','Read And Modify'], correct:'B' },
    { id:'e4', text:'What is a web browser used for?', options:['Playing games','Browsing the internet','Editing documents','Sending SMS'], correct:'B' },
    { id:'e5', text:'Which of the following is an example of AI in daily life?', options:['A calculator','A voice assistant like Siri','A light bulb','A paper notebook'], correct:'B' },
    { id:'e6', text:'What does "www" stand for?', options:['World Wide Web','Wireless Wide Web','World Web Wireless','Wide World Web'], correct:'A' },
    { id:'e7', text:'Which of the following is an input device?', options:['Monitor','Printer','Keyboard','Speaker'], correct:'C' },
    { id:'e8', text:'What does URL stand for?', options:['Uniform Resource Locator','Universal Resource Link','Unique Reference Locator','Uniform Record Locator'], correct:'A' },
    { id:'e9', text:'What is software?', options:['Physical parts of a computer','Programs that run on a computer','The screen of a computer','Cables and wires'], correct:'B' },
    { id:'e10', text:'What is hardware?', options:['Programs installed on a computer','Operating system files','Physical parts of a computer','Internet connection'], correct:'C' },
    { id:'e11', text:'Which of these is a storage device?', options:['Keyboard','Mouse','Hard Disk','Monitor'], correct:'C' },
    { id:'e12', text:'What does "GB" stand for in computer storage?', options:['General Byte','Gigabyte','Global Bit','Giga Base'], correct:'B' },
    { id:'e13', text:'What is the internet?', options:['A type of computer program','A global network of connected computers','A storage device','A type of software'], correct:'B' },
    { id:'e14', text:'What does "OS" stand for in computing?', options:['Online System','Open Software','Operating System','Output Screen'], correct:'C' },
    { id:'e15', text:'Which company created the Windows operating system?', options:['Apple','Google','Microsoft','Samsung'], correct:'C' },
    { id:'e16', text:'What is a robot?', options:['A type of AI software only','A machine that can perform tasks automatically','A video game character','A type of network'], correct:'B' },
    { id:'e17', text:'What does "email" stand for?', options:['Easy mail','Electronic mail','External mail','Express mail'], correct:'B' },
    { id:'e18', text:'What is a monitor used for?', options:['Storing data','Printing documents','Displaying output from a computer','Processing calculations'], correct:'C' },
    { id:'e19', text:'Which of the following is an output device?', options:['Keyboard','Scanner','Microphone','Printer'], correct:'D' },
    { id:'e20', text:'What is the main purpose of an operating system?', options:['To play music','To manage computer hardware and software resources','To browse the internet','To create documents'], correct:'B' },
    { id:'e21', text:'What does AI primarily try to do?', options:['Replace all humans','Make machines think and learn like humans','Make computers faster only','Store more data'], correct:'B' },
    { id:'e22', text:'What does Wi-Fi allow you to do?', options:['Print documents faster','Connect to the internet wirelessly','Store more files','Speed up the CPU'], correct:'B' },
    { id:'e23', text:'What is a computer virus?', options:['A type of hardware problem','A harmful program that damages computers','A slow internet connection','A broken keyboard'], correct:'B' },
    { id:'e24', text:'What is a search engine?', options:['A car engine run by computers','A tool to find information on the internet','A type of printer','A hardware component'], correct:'B' },
    { id:'e25', text:'What does "click" mean on a computer?', options:['Turn off the computer','Press a mouse button to select something','Type on the keyboard','Save a file'], correct:'B' },
  ],

  medium: [
    { id:'m1', text:'Which type of machine learning uses labeled data to train a model?', options:['Unsupervised learning','Supervised learning','Reinforcement learning','Random learning'], correct:'B' },
    { id:'m2', text:'What is a neural network inspired by?', options:['The structure of a computer chip','The human brain and nervous system','The internet structure','A mathematical equation only'], correct:'B' },
    { id:'m3', text:'What does NLP stand for in AI?', options:['Network Layer Protocol','Natural Language Processing','Neural Learning Program','Numeric Logic Processing'], correct:'B' },
    { id:'m4', text:'What is a firewall used for in networking?', options:['Increasing internet speed','Blocking unauthorized access to a network','Storing passwords','Compressing files'], correct:'B' },
    { id:'m5', text:'What is "cloud computing"?', options:['Computing done in rainy weather','Storing and accessing data and programs over the internet','A type of hardware','A local storage device'], correct:'B' },
    { id:'m6', text:'What does IP address stand for?', options:['Internet Password address','Internet Protocol address','Internal Program address','Input Processing address'], correct:'B' },
    { id:'m7', text:'What is a database?', options:['A type of computer game','An organized collection of structured data','A hardware component','A type of virus'], correct:'B' },
    { id:'m8', text:'What is encryption used for?', options:['Making files smaller','Securing data by converting it to an unreadable format','Speeding up downloads','Organizing files'], correct:'B' },
    { id:'m9', text:'What does "phishing" mean in cybersecurity?', options:['Fishing for computer bugs','Tricking users into revealing personal information','A type of encryption','Scanning for viruses'], correct:'B' },
    { id:'m10', text:'What is the primary difference between AI and traditional programs?', options:['AI uses more electricity','AI can learn and improve from data; traditional programs follow fixed rules','Traditional programs are faster','AI only works on supercomputers'], correct:'B' },
    { id:'m11', text:'Which of these is a programming language?', options:['HTML only (it is a markup language)','Microsoft Word','Python','Google Chrome'], correct:'C' },
    { id:'m12', text:'What is an algorithm?', options:['A type of computer virus','A step-by-step procedure to solve a problem','A hardware component','A type of AI robot'], correct:'B' },
    { id:'m13', text:'What is "machine learning"?', options:['Teaching machines to do physical work','A type of AI where systems learn from data without being explicitly programmed','A programming language','A type of computer memory'], correct:'B' },
    { id:'m14', text:'What is computer vision?', options:['A computer monitor with high resolution','AI ability to interpret and understand images and video','A type of keyboard shortcut','A graphics design software'], correct:'B' },
    { id:'m15', text:'What does "debugging" mean in programming?', options:['Adding new features to code','Finding and fixing errors in a program','Deleting a program','Uploading code to the internet'], correct:'B' },
    { id:'m16', text:'What is binary code?', options:['A secret language used by hackers','A system using only 0s and 1s to represent data','A type of programming language','A method of file compression'], correct:'B' },
    { id:'m17', text:'What does two-factor authentication do?', options:['Makes passwords shorter','Requires two forms of verification to log in, improving security','Automatically changes passwords','Blocks all logins except admin'], correct:'B' },
    { id:'m18', text:'What is the Internet of Things (IoT)?', options:['A new social media platform','Everyday physical devices connected to the internet','A type of programming language','A video streaming service'], correct:'B' },
    { id:'m19', text:'What is a server in computing?', options:['A person who serves food','A computer that provides services and data to other computers','A type of keyboard','A hardware repair tool'], correct:'B' },
    { id:'m20', text:'What does bandwidth measure in networking?', options:['The physical size of cables','The data transfer capacity of a network connection','The number of devices connected','The speed of a CPU'], correct:'B' },
    { id:'m21', text:'What is a variable in programming?', options:['A type of loop','A container that stores a data value','A function that returns results','A type of error'], correct:'B' },
    { id:'m22', text:'What is artificial general intelligence (AGI)?', options:['AI that plays games','AI capable of performing any intellectual task that a human can','A type of robot','AI that only processes images'], correct:'B' },
    { id:'m23', text:'What is open source software?', options:['Software that costs nothing to buy','Software whose source code is publicly available and can be modified','Software made by open companies','Software used on open networks'], correct:'B' },
    { id:'m24', text:'What is a sorting algorithm primarily used for?', options:['Encrypting data','Arranging data in a specific order','Connecting to networks','Generating passwords'], correct:'B' },
    { id:'m25', text:'What is the purpose of a cache in computing?', options:['To delete old files','To temporarily store frequently accessed data for faster retrieval','To block viruses','To encrypt files'], correct:'B' },
  ],

  hard: [
    { id:'h1', text:'A computer vision system is trained on thousands of images labeled "cat" and "dog". What is it primarily learning to do?', options:['Compress the images','Classify new images based on learned visual patterns','Increase image resolution','Store images permanently'], correct:'B' },
    { id:'h2', text:'What is backpropagation in neural networks?', options:['Moving data backwards through memory','An algorithm that adjusts network weights by calculating error gradients','A method of data encryption','A technique for compressing neural networks'], correct:'B' },
    { id:'h3', text:'What problem does overfitting cause in machine learning?', options:['The model trains too slowly','The model performs well on training data but poorly on unseen data','The model uses too much memory','The model produces random results'], correct:'B' },
    { id:'h4', text:'What is the Turing Test designed to evaluate?', options:['A computer\'s processing speed','Whether a machine can exhibit intelligent behavior indistinguishable from a human','The security of a system','A computer\'s memory capacity'], correct:'B' },
    { id:'h5', text:'What is transfer learning in AI?', options:['Moving AI programs between computers','Using a pre-trained model as a starting point for a new related task','Transferring data between AI systems','A method of data augmentation'], correct:'B' },
    { id:'h6', text:'In a binary search of 1024 sorted elements, what is the maximum number of comparisons needed?', options:['1024','512','10','100'], correct:'C' },
    { id:'h7', text:'What is the role of an activation function in a neural network?', options:['To initialize weights','To introduce non-linearity so the network can learn complex patterns','To normalize input data','To connect layers together'], correct:'B' },
    { id:'h8', text:'What does "gradient descent" do during machine learning training?', options:['Increases model complexity','Minimizes the loss function by iteratively adjusting model parameters','Shuffles training data','Removes unnecessary neurons'], correct:'B' },
    { id:'h9', text:'What is a Convolutional Neural Network (CNN) primarily designed for?', options:['Processing audio signals','Image recognition and visual pattern extraction','Natural language translation','Financial predictions'], correct:'B' },
    { id:'h10', text:'What is a Recurrent Neural Network (RNN) best suited for?', options:['Image classification','Static data analysis','Sequential data like text, speech, and time series','Random data generation'], correct:'C' },
    { id:'h11', text:'What does "bias" mean in the context of AI fairness?', options:['A model that runs too fast','Systematic errors in AI outputs caused by flawed or unrepresentative training data','A type of neural network layer','A programming mistake'], correct:'B' },
    { id:'h12', text:'What does Big O notation describe in computer science?', options:['The physical size of an algorithm','The time or space complexity of an algorithm as input size grows','The number of bugs in code','The memory used by a variable'], correct:'B' },
    { id:'h13', text:'What is a hash function used for in cybersecurity?', options:['Generating random passwords','Converting data of any size into a fixed-size string for secure storage and verification','Encrypting entire files','Compressing images'], correct:'B' },
    { id:'h14', text:'What does a SQL injection attack do?', options:['Slows down a database','Inserts malicious code into database queries to gain unauthorized access','Encrypts database files','Deletes all users from a database'], correct:'B' },
    { id:'h15', text:'What is federated learning?', options:['Learning from multiple teachers','Training AI models across multiple devices without sharing raw personal data','A government-funded AI program','Combining multiple AI models into one'], correct:'B' },
    { id:'h16', text:'What does "precision" measure in a machine learning classifier?', options:['Overall model accuracy','The ratio of true positives to all predicted positives','The speed of classification','Training data quality'], correct:'B' },
    { id:'h17', text:'What is a hyperparameter in machine learning?', options:['A very large parameter','A configuration set before training that controls the learning process (e.g., learning rate)','A parameter that changes during training','The final output of a model'], correct:'B' },
    { id:'h18', text:'Which data structure uses FIFO (First In, First Out) ordering?', options:['Stack','Tree','Queue','Graph'], correct:'C' },
    { id:'h19', text:'What is quantum computing based on?', options:['Very fast traditional processors','Quantum bits (qubits) that can represent 0, 1, or both simultaneously','Quantum physics simulations only','A new type of binary code'], correct:'B' },
    { id:'h20', text:'What is reinforcement learning?', options:['Learning by memorizing data','Training agents by rewarding correct actions and penalizing incorrect ones','A form of supervised learning','Learning from labeled datasets'], correct:'B' },
    { id:'h21', text:'What is a GAN (Generative Adversarial Network)?', options:['A network for detecting viruses','Two neural networks that compete to generate realistic synthetic data','A type of recurrent network','A network that classifies text'], correct:'B' },
    { id:'h22', text:'What is the "vanishing gradient" problem in deep learning?', options:['Gradients growing too large and causing instability','Gradients becoming extremely small during backpropagation, slowing or stopping learning','A memory overflow error','A type of overfitting'], correct:'B' },
    { id:'h23', text:'What does "tokenization" mean in Natural Language Processing?', options:['Generating security tokens','Breaking text into individual words, subwords, or characters for processing','Converting text to numbers','Translating between languages'], correct:'B' },
    { id:'h24', text:'What ethical issue arises when AI systems are trained on biased data?', options:['The AI becomes slower','The AI may produce discriminatory or unfair outcomes for certain groups','The AI requires more memory','The AI becomes less accurate on all data'], correct:'B' },
    { id:'h25', text:'What is the purpose of the convolutional layer in a CNN?', options:['To make final predictions','To extract features like edges, textures, and shapes from images','To normalize input data','To connect to the output layer'], correct:'B' },
  ]
};

module.exports = QUESTIONS;
